### ISSUE TITLE
Image component | Sanitize input

### ISSUE THREAD

**Issue by evegufy** [eclipse-tractusx/portal-shared-components#117]
### Description

Sanitize input from a React useState value flows into a script 'src' attribute, where it is used to dynamically construct the HTML page on client side:
https://github.com/eclipse-tractusx/portal-shared-components/blob/v2.1.42/src/components/basic/Image/index.tsx#L77

### Additional information

[Maybe useful for fixing](https://learn.snyk.io/lesson/dom-based-xss/?_gl=1*1avghsl*_ga*NzI0NTM5NzMwLjE3MDQ4MDM4MTY.*_ga_X9SH3KP7B4*MTcxMTUyNjUxOC4zOS4xLjE3MTE1Mjc3NTQuMC4wLjA.)

**Comment by oyo** [comment]
This code is intended to create an HTML image tag and sanitizing at this point is not very helpful as our Image component is simply an alternative to the default HTML <img>, MUI or any other Image component. The src attribute is only handed over to the default img tag or a loader function. If application developers decide to use any other image component the issue is still there.
