### ISSUE TITLE
Simplify and automate release versioning

### ISSUE THREAD

**Issue by oyo** [eclipse-tractusx/portal-shared-components#196]
### Description

We like to introduce a change in the release process as currently it is not optimal for several reasons:

- the library is released on every merge - this seems sometimes unnecessary as some changes don't affect the code like updating license headers. Also when we merge several PRs at the same time why do we need to publish a separate release for each one? This is a waste of compute resources on GitHub Actions and storage on NPM repos.
- developers have to spend additional efforts to manually set the version number for the release
- especially when multiple PRs are open developers don't know the sequence number of "their" release and we get merge conflicts in CHANGELOG.md and have to frequently update their PRs to resolve those.

The improved process would look like this:

- developers only raise PRs for their changes without caring about release or version number
- committers review, approve and merge those PRs to main (without triggering a new release)
- independent from the merge committers can decide to release at any time by pushing a git annotated tag which would trigger an action run that automatically updates package.json and CHANGELOG.md setting version and change messages. Note that they are still free to publish a release after each merge if that should seem appropriate.

### Acceptance Criteria

- [ ] PRs don't need to include updates for package.json and CHANGELOG.md
- [ ] No release is triggered after merge
- [ ] Pushing a git annotated tag will trigger an automated update to package.json and CHANGELOG.md and publish a new release

### Additional Information
example release trigger command
`git tag -a "v3.0.16" -m "* Added feature X" -m "* Fixed bug Y" -m "* Changed behavior Z"`
`git push --tags`

**Comment by evegufy** [comment]
Hi @oyo, IMO the release process works quite well but sure could be improved as an enhancement, generally I'd change then to a bit more automated process than you describe with creating tags manually. 
- I think the version bump when raising a PR should just not be in the pre-checks as obligatory
- In case someone wants release a new version with one specific PR, the version in the package.json is bump
- When merging into main, the release workflow checks if a version bump occurred or not acts accordingly
- When a bump occurred the publishing to NPM is triggered and as a result a tag is created
See https://github.com/eclipse-tractusx/policy-hub/blob/main/.github/workflows/release.yml#L66 for a similar workflow just with Chart.yaml instead of package.json and build of docker images instead of publishing to NPM

**Comment by oyo** [comment]
> Hi @oyo, IMO the release process works quite well but sure could be improved as an enhancement, generally I'd change then to a bit more automated process than you describe with creating tags manually.
> 
> * I think the version bump when raising a PR should just not be in the pre-checks as obligatory
> * In case someone wants release a new version with one specific PR, the version in the package.json is bump
> * When merging into main, the release workflow checks if a version bump occurred or not acts accordingly
> * When a bump occurred the publishing to NPM is triggered and as a result a tag is created
>   See https://github.com/eclipse-tractusx/policy-hub/blob/main/.github/workflows/release.yml#L66 for a similar workflow just with Chart.yaml instead of package.json and build of docker images instead of publishing to NPM

@evegufy this doesn't solve the biggest issue - constantly fixing merge conflicts in CHANGELOG.md

**Comment by evegufy** [comment]
> > Hi @oyo, IMO the release process works quite well but sure could be improved as an enhancement, generally I'd change then to a bit more automated process than you describe with creating tags manually.
> > 
> > * I think the version bump when raising a PR should just not be in the pre-checks as obligatory
> > * In case someone wants release a new version with one specific PR, the version in the package.json is bump
> > * When merging into main, the release workflow checks if a version bump occurred or not acts accordingly
> > * When a bump occurred the publishing to NPM is triggered and as a result a tag is created
> >   See https://github.com/eclipse-tractusx/policy-hub/blob/main/.github/workflows/release.yml#L66 for a similar workflow just with Chart.yaml instead of package.json and build of docker images instead of publishing to NPM
> 
> @evegufy this doesn't solve the biggest issue - constantly fixing merge conflicts in CHANGELOG.md when multiple PRs are opened at the same time

@oyo the CHANGELOG.md doesn't need to be updated with every PR if that causes issues, then let's just update the changelog when creating a PR containing a version bump in package.json, that's also completely fine (in the portal-backend repo for instance the changelog is only updated at release, updating the changelog is something specific to portal-frontend, and I figured that's because you think it's beneficial).
The downside of not maintaining the changelog with every PR is that then someone needs to maintain the entire changelog at the release.
FYI, for the new repos I moved to a automated Changelog creation according to PR titles:
https://github.com/eclipse-tractusx/policy-hub/blob/main/CHANGELOG.md
https://github.com/eclipse-tractusx/policy-hub/blob/main/docs/technical-documentation/release-process/Release%20Process.md#update-changelogmd
But that's difficult for the portal repos. as there's the issue of poor PR title maintenance of the past... as the portal-shared-components is relatively new, we could at least try it out, what do you think?

**Comment by jjeroch** [comment]
Ticket refined; pushing it into the backlog

**Comment by shahmargi12** [comment]
Hi @oyo  and @evegufy ,

I have gone through this issue and would like to contribute. Below is the approach that I have implemented:

**Step 1: PR Validation**

**1. Check Version Bump:**
**a.** If the package version in the PR is lower than the current published version (e.g., published version is **0.0.42** and PR version is **0.0.41**), return an error: "Please update the package version to the correct version."
**b.** If the package version is not bumped (i.e., it is the same as the published version), allow the PR to proceed to the next step without errors.
**c.** If the package version is bumped, one commit message is displayed in GitHub action which user have to copy and run in their local and update the PR.
commit message  - 'git commit --allow-empty -m "chore: release 0.0.20" -m "Release-As: 0.0.20"

**Step 2: Post-Merge Actions**
**1. Check Version Again:**
**a.** After the PR is merged, check if the package version has been bumped.
**b.** If the version is bumped, proceed with the **build-and-publish job**. If not, skip this step.

**Step 3: Build and publish job**
**1. During the build-and-publish job:**
**a.** Create a PR using release-please that includes updates to the CHANGELOG.md file, summarizing all commits made after the last release.
**b.** Once the release PR (created by the dependent bot) is merged by user (who has merge access), the release is created, followed by tag creation and package publish step.

**Key Notes:**

**Release PR:** The release process is fully automated, with the changelog PR generated and needs to be merged by an authenticated user to trigger the final release and then publish the package to npm.

**Empty Commit for Release:** The empty commit serves as a marker indicating that the release process should proceed.

This refactor streamlines the process while ensuring version integrity and automated release management. Does this align with your requirements, or do you need further adjustments?

**Comment by MaximilianHauer** [comment]
@oyo  / @evegufy  can we close it ?
